dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install .
script:
  - make test
  - make lint
after_success:
  - codecov
