project = 'DBGR'
copyright = '2019, Jakub Tesárek'
author = 'Jakub Tesárek'
release = '1.1.0'
extensions = []
templates_path = ['_templates']
exclude_patterns = []
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
master_doc = 'index'
